### ISSUE TITLE
VirusTotal detects Trojan.PSW.Python.bp in ChronoPlotter.exe

### ISSUE THREAD

**Issue by erichiggins** [mncoppola/ChronoPlotter#1]
Bringing this to your attention, in case you are not yet aware.

**Reference:** https://www.virustotal.com/gui/file/8bf43a3416b52ae0cc37e9032ccf4fd8598d3461656566d6675967d1c1a7ec22/detection

**Comment by mncoppola** [comment]
Thanks for the heads up. Yeah, anti-viruses haven't been playing too well with PyInstaller. I'm currently building the PyInstaller bootloader from source with each release (instead of using the prebuilt one) which has significantly helped the issue. Hitting zero false positives is on the list though, either through further code changes or maybe Windows code signing.

**Comment by erichiggins** [comment]
Cool. Perhaps this may help?

https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg/52054580#52054580

**Comment by mncoppola** [comment]
Thanks, yup I'm currently doing that actually https://github.com/mncoppola/ChronoPlotter/blob/main/azure-pipelines.yml#L41

**Comment by mncoppola** [comment]
Just an update, I'm mid-way through rewriting ChronoPlotter from the ground-up in C++. This will drop the PyInstaller dependency which will be a huge benefit (for a variety of reasons, including anti-virus false detections). It'll also make it easier to perform Windows code signing, which will additionally help with SmartScreen warnings on recent Windows.

**Comment by mncoppola** [comment]
I just released v2.0.0 which brings a full project rewrite in C++. This drops PyInstaller completely, which should solve this issue.
